apiVersion: apps/v1
kind: Deployment
metadata:
  name: commande-service
  labels:
    app: commande-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commande-service
  template:
    metadata:
      labels:
        app: commande-service
    spec:
      containers:
        - name: commande-service
          image: ibrahimkr/commande:v1.0
          ports:
            - containerPort: 8081
          env:
            - name: PRODUIT_SERVICE_URL
              value: http://produit-service:8081/products/
---
apiVersion: v1
kind: Service
metadata:
  name: commande-service
spec:
  selector:
    app: commande-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
